// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  call_to_action: dynamic(() => import("./CallToAction")),
  card_with_category: dynamic(() => import("./CardWithCategory")),
  carousel_gallery: dynamic(() => import("./CarouselGallery")),
  featured_content_gallery: dynamic(() => import("./FeaturedContentGallery")),
  hero: dynamic(() => import("./Hero")),
  navigation_menu: dynamic(() => import("./MenuItem")),
  texte: dynamic(() => import("./Texte")),
};
